name: Test kubectl
on:
  push:
    branches: [ master ]

jobs:
  test_kubectl:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Install kubectl
      run: |
        echo $PATH
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        chmod +x kubectl
        mkdir -p ~/.local/bin/kubectl
        mv ./kubectl ~/.local/bin/kubectl
    - name: Save kubeconfig to github var
      # kubeconfig path is saved as github var to be used by helm
      run: |
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > $RUNNER_TEMP/config
        echo "kubeconfig=$RUNNER_TEMP/config" >> $GITHUB_ENV
    - name: Test kubectl
      env:
        KUBECONFIG: "${{ env.kubeconfig }}"
      run: |
        sudo su
        kubectl cluster-info
        kubectl get pods -A

