name: Shell Commands

on:
  push:
    branches:
      - "testing"


jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello from runner"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: run python command
        run: |
          import platform
          print(platform.processor())
        shell: python